### PR TITLE
Add asyncIterator implementation

### PR DESCRIPTION
**Pull request by kewisch**
I'd like to do this:

```javascript
let zipFile = await yauzl.open("...");
for await (let entry of zipFile) {
  // do magic
}
await zipFile.close();
```

### CODE REVIEW

**Comment by overlookmotel** [comment]
Thanks for submitting this PR.

However, I see you altered Travis config and package.json to make this package only support Node v10+. I'm OK to drop support for Node v6 as it's EOL, but do want to continue to support Node v8 as it's a current version of Node.

Can you find a way to implement which does not drop support for Node v8?

Also, can you please add something to README which explains usage?

**Comment by kewisch** [comment]
I was thinking of adding something to the readme, but then thought it might be better for #7 which I could definitely send a PR for afterwards.

Regarding node v8, I'll see if I can identify the missing features and work around it. It is possible that I might just have to disable or rewrite the test because node 8 doesn't support `for await(...of...)`. I do want to avoid adding babel to the mix :)

**Comment by overlookmotel** [comment]
I don't think you actually need to use `for(await)` in the code itself - you can emulate an async iterator.

For the test, yes you'll likely need to disable that test on Node 8. You may need to put the test in a separate file and only `require()` it on Node 10+ to avoid a syntax error in Node 8.

**Comment by kewisch** [comment]
Yes, I was thinking the same. If we drop node 6 then we can use async functions, which makes it easy to support 8 and 10+ without making the code too convoluted. I missed that async generators are not supported in node 8, looking into that now.

**Comment by kewisch** [comment]
Ok, this looks good to go from my end. I'll fix the docs in a separate PR for #7. Please squash and merge when you've reviewed :)

**Comment by kewisch** [comment]
Hey, just checkin in on this. Looks good?

**Comment by kewisch** [comment]
Is this good to merge?

**Comment by paya-cz** [comment]
It is unfortunate this never got merged. Perhaps this package is abandoned?

**Comment by kewisch** [comment]
Wondering where we are on this. Any chance for a merge?

**Comment by overlookmotel** [comment]
Well it took me 3 years! This is now implemented in v3.0.0.

**Comment by kewisch** [comment]
Nice, glad you found the time!

**Pull request closed without merging**
